### ISSUE TITLE
Compile failed after upgrade to 2.57.0

### ISSUE THREAD

**Issue by Gaojianli** [arco-design/arco-design-vue#3489]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue@2.57.0
- **框架版本:** 3.5.13
- **浏览器版本:** chrome134.0.0.0

## 预期结果
No error

## 复现步骤
Just upgrade the arco-design-vue from 2.56.3 to 2.57.0
```vue
 <a-split :size="0.5" disabled>
.....
</a-split>
```
```
src/views/settings/components/info/index.vue:8:6 - error TS2345: Argument of type '{ size: number; disabled: true; }' is not assignable to parameter of type 'Partial<{ disabled: boolean; size: string | number; direction: "horizontal" | "vertical"; component: string; defaultSize: string | number; }> & Omit<{ readonly component: string; ... 9 more ...; readonly "onUpdate:size"?: ((size: string | number) => any) | undefined; } & VNodeProps & AllowedComponentProps & Componen...'.
  Type '{ size: number; disabled: true; }' is missing the following properties from type 'Omit<{ readonly component: string; readonly direction: "horizontal" | "vertical"; readonly size: string | number | undefined; readonly defaultSize: string | number; readonly min: string | number | undefined; ... 5 more ...; readonly "onUpdate:size"?: ((size: string | number) => any) | undefined; } & VNodeProps & All...': max, min

8     <a-split :size="0.5" disabled>
       ~~~~~~~
```
![Image](https://github.com/user-attachments/assets/112032ab-abfa-472a-82f4-8c7d7ef75491)

Also: where is the changelog of 2.57.0?
